[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/","@biconomy/contracts=lib/scw-contracts/contracts/smart-contract-wallet"]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"







# See more config options https://github.com/foundry-rs/foundry/tree/master/config